import { Offer } from "@/types";

export const offers: Offer[] = [
  // LEGAL SERIES
  {
    id: "legal-debt-mastery",
    name: "Debt Defense Mastery™",
    category: "legal",
    price: "$47",
    priceUnit: "one-time · instant access",
    tierLabel: "Course · $47",
    shortDescription:
      "Comprehensive step-by-step course on how to respond to a debt collection lawsuit. Covers the entire process from summons to trial — written for self-represented individuals in any state.",
    deliverables: [
      "7 modules · 30 PDF lessons",
      "Answer templates + affirmative defenses",
      "Discovery request templates",
      "Trial preparation guide",
      "Settlement negotiation scripts",
    ],
    ctaLabel: "Enroll",
  },
  {
    id: "legal-strategy-session",
    name: "Legal Strategy Session",
    category: "legal",
    price: "$97",
    priceUnit: "per session",
    tierLabel: "⭐ Most Popular",
    shortDescription:
      "60 minutes of focused, one-on-one legal coaching. Walk through your situation together. Understand the process, timeline, documents, and questions you need to be asking.",
    deliverables: [
      "60-minute 1:1 session by phone or video",
      "Document review and process education",
      "Written session summary provided",
      "Upgrade to 90-min Court Walkthrough available",
    ],
    ctaLabel: "Book Now",
    featured: true,
  },
  {
    id: "legal-court-walkthrough",
    name: "Court Process Walkthrough",
    category: "legal",
    price: "$127",
    priceUnit: "per session",
    tierLabel: "Session · $127",
    shortDescription:
      "90-minute deep-dive session with document review. Bring your summons, motions, minute orders, or discovery — we go through every document so you understand exactly what's happening and what comes next.",
    deliverables: [
      "90-minute session + document review",
      "Deadline calculation and court calendar review",
      "Next-steps action plan",
      "Written session summary",
    ],
    ctaLabel: "Book Now",
  },
  {
    id: "legal-coaching-program",
    name: "Self-Rep Litigant Coaching Program",
    category: "legal",
    price: "$297",
    priceUnit: "3-session / $397 4-session",
    tierLabel: "Full Program",
    shortDescription:
      "Multi-session coaching for people actively representing themselves in court. From summons to resolution — court rules, filing, hearing preparation, case organization, and strategy education throughout your case.",
    deliverables: [
      "3-session package at $297",
      "4-session package at $397",
      "Email support between sessions",
      "Case file organization system",
      "Hearing preparation coaching",
    ],
    ctaLabel: "Get Started",
    featured: true,
  },
  {
    id: "legal-template-bundle",
    name: "Legal Document Template Bundle",
    category: "legal",
    price: "$37",
    priceUnit: "one-time · instant download",
    tierLabel: "Templates · $37",
    shortDescription:
      "Ready-to-use legal document templates for self-represented defendants. Written for general use across any U.S. state — you adapt them to your specific situation.",
    deliverables: [
      "General denial Answer template",
      "Affirmative defenses library",
      "Interrogatories template (20 questions)",
      "Request for Production template",
      "Proof of Service form",
    ],
    ctaLabel: "Download",
  },
  {
    id: "legal-async-support",
    name: "Monthly Async Support",
    category: "legal",
    price: "$97",
    priceUnit: "per month · cancel anytime",
    tierLabel: "Monthly · $97",
    shortDescription:
      "Written coaching and question-answering via email or message. Submit questions about your legal matter and receive educational guidance within 48 hours. Ongoing support throughout your case.",
    deliverables: [
      "Unlimited written questions monthly",
      "48-hour response time",
      "Document review feedback (educational)",
      "Cancel anytime",
    ],
    ctaLabel: "Subscribe",
  },

  // CREDIT SERIES
  {
    id: "credit-starter-kit",
    name: "Credit Repair Starter Kit™",
    category: "credit",
    price: "$47",
    priceUnit: "one-time · instant access",
    tierLabel: "Tier 1 · $47",
    shortDescription:
      "The foundation of credit empowerment. Modules 1–3 walk you through understanding your score, reading your credit reports across all three bureaus, and running your own dispute process step by step.",
    deliverables: [
      "3 modules · 12 PDF lessons",
      "FICO factors deep-dive guide",
      "Credit report annotation worksheet",
      "Dispute letter templates (3 bureaus)",
      "Dispute tracking worksheet",
    ],
    ctaLabel: "Enroll",
  },
  {
    id: "credit-mastery-blueprint",
    name: "Credit Mastery Blueprint™",
    category: "credit",
    price: "$97",
    priceUnit: "one-time · instant access",
    tierLabel: "⭐ Full Course",
    shortDescription:
      "The complete credit transformation system. All 7 modules covering the full spectrum — from disputes and building credit to FICO optimization, debt management, and maintaining excellent credit for life.",
    deliverables: [
      "7 modules · 30 PDF lessons (complete)",
      "Full dispute system + advanced strategies",
      "Credit building from scratch guide",
      "FICO optimization toolkit",
      "Pay-for-delete + goodwill letter templates",
      "Debt negotiation scripts",
    ],
    ctaLabel: "Enroll Now",
    featured: true,
  },
  {
    id: "credit-template-bundle",
    name: "Credit Dispute Template Bundle",
    category: "credit",
    price: "$37",
    priceUnit: "one-time · instant download",
    tierLabel: "Templates · $37",
    shortDescription:
      "Every letter you need to dispute errors, validate debts, request goodwill removals, and negotiate pay-for-delete agreements — professionally written and ready to customize.",
    deliverables: [
      "Bureau dispute letter (all 3 bureaus)",
      "Debt validation letter (FCRA/FDCPA)",
      "Pay-for-delete negotiation letter",
      "Goodwill removal request letter",
      "CFPB complaint template",
    ],
    ctaLabel: "Download",
  },
  {
    id: "credit-strategy-session",
    name: "Credit Strategy Session",
    category: "credit",
    price: "$97",
    priceUnit: "per session",
    tierLabel: "Session · $97",
    shortDescription:
      "60-minute one-on-one credit coaching session. Review your credit reports together, identify your biggest score factors, and build a personalized action plan based on your specific credit goals.",
    deliverables: [
      "60-minute 1:1 session by phone or video",
      "Credit report review and education",
      "Personalized action plan",
      "Written session summary",
    ],
    ctaLabel: "Book Now",
  },
  {
    id: "credit-monthly-support",
    name: "Credit Coaching — Monthly Support",
    category: "credit",
    price: "$97",
    priceUnit: "per month · cancel anytime",
    tierLabel: "Monthly Support",
    shortDescription:
      "Ongoing credit education and coaching via email or message. Submit questions, get dispute guidance, track your progress, and receive educational support through your entire credit repair journey.",
    deliverables: [
      "Unlimited written questions monthly",
      "48-hour response time",
      "Progress tracking check-ins",
      "Dispute strategy guidance (educational)",
      "Cancel anytime",
    ],
    ctaLabel: "Subscribe",
    featured: true,
  },
];
